- hosts: all 
  become: root
  tasks:
     - name: create now deployement
       command: kubectl apply -f /home/ubuntu/Deployent.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yml
