apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrdevops
  labels:
    app: nginx
spec:
  replicas: 2
  selector:  #tel the controller which pods to watch/bolong to
    matchLabels: 
      app: mrdevops
  template:
    metadata:
      labels:
        app: mrdevops
    spec:
      containers:
      - name: mrdevops
        image: devopsdockerreg/kubernetes-project
        imagePullPolicy: Always
        ports:
        - containerPort: 80
